spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://cs6156hwdb0.culd69w38gsx.us-east-1.rds.amazonaws.com:3306/intellipro?characterEncoding=utf-8&useSSL=false
      username: root
      password: awdjk123
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 80

